# Generated by Django 5.0.3 on 2024-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_salarypayment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageleave',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
    ]
